# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('probing', ['core', 'internet', 'clove', 'xpath-routing'])
    module.source = [
        'model/ipv4-probing.cc',
        'helper/probing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('probing')
    module_test.source = [
        'test/probing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'probing'
    headers.source = [
        'model/ipv4-probing.h',
        'helper/probing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

